version: 2
jobs:
  build:
    docker:
      - image: library/docker:16.04
    working_directory: /go/src/github.com/RisingStack/almandite-user-service
    steps:
      - checkout
      - run: docker build . -t almandite-user-service

  test:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/RisingStack/almandite-user-service
    steps:
      - checkout
      - run: curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
      - run: make deps
      - run: make test
      